Ensure options are registered for unit testing
As part of commit [1] we moved the register options to a function,
that means unit tests need to be updated to register those option
in the setup if they are needed, otherwise we can get errors like:

Captured traceback:
~~~~~~~~~~~~~~~~~~~
Traceback (most recent call last):
  File "/builddir/build/BUILD/ovn-bgp-agent-0.3.1.dev112/ovn_bgp_agent/tests/unit/drivers/openstack/watchers/test_bgp_watcher.py", line 878, in test_run_no_subnets_datapath
    CONF.set_override('expose_tenant_networks', False)
  File "/usr/lib/python3.9/site-packages/oslo_config/cfg.py", line 2059, in __inner
    result = f(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/oslo_config/cfg.py", line 2442, in set_override
    opt_info = self._get_opt_info(name, group)
  File "/usr/lib/python3.9/site-packages/oslo_config/cfg.py", line 2858, in _get_opt_info
    raise NoSuchOptError(opt_name, group)
oslo_config.cfg.NoSuchOptError: no such option expose_tenant_networks in group [DEFAULT]

[1] https://opendev.org/openstack/ovn-bgp-agent/commit/90b6940b2148b63bbd38f8b657346f54770b4524

Change-Id: I138ab9a4ed6f7b1d0138129c00362f603fc4320a